services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./ollama_data:/root/.ollama
    environment:
      - OLLAMA_NUM_GPU=65
    # Опционально: если есть GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Сервис, который скачает модель и выключится
  ollama-puller:
    image: curlimages/curl:latest
    container_name: ollama-puller
    depends_on:
      - ollama
    entrypoint: [ "sh", "-c", "sleep 5 && curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"qwen2.5-coder:32b\"}'" ]


#  litellm:
#    image: ghcr.io/berriai/litellm:main-latest
#    ports:
#      - "4000:4000"
#    environment:
#      - OLLAMA_API_BASE=http://ollama:11434
#    command: [ "--model", "ollama/qwen2.5-coder:7b" ]

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    depends_on:
      - ollama
    ports:
      - "4000:4000"
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
    command: [ "--model", "ollama/qwen2.5-coder:32b", "--alias", "claude-sonnet-4-6:ollama/qwen2.5-coder:32b", "--drop_params", "--enable_tool_use" ]


