# docker-compose.yml
services:
  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    command: ["--config", "/app/config.yaml", "--port", "4000", "--detailed_debug"]
    #environment:
    #  - LITELLM_MASTER_KEY=sk-local-key-1234  # Claude Code будет использовать этот ключ
    extra_hosts:
      - "host.docker.internal:host-gateway"  # чтобы достучаться до Ollama на хосте
    restart: unless-stopped